/* DADOS SINTÉTICOS — usado apenas para desenvolvimento */

import type { Produto, Categoria } from "./types";

export const produtos: Produto[] = [
  {
    id: "1",
    nome: "Vestido Flor",
    descricao: "Vestido florido em viscose. Leve, fresco, ideal para dias quentes. Botões frontais, cintura marcada.",
    preco: 8990,
    categoria: "Vestidos",
    tamanhos: ["P", "M", "G"],
    fotos: ["https://placehold.co/400x600?text=Vestido+Flor"],
    disponivel: true,
    createdAt: "2026-07-28T10:00:00Z",
  },
  {
    id: "2",
    nome: "Blusa Transpassada",
    descricao: "Blusa em crepe com amarração lateral. Decote V, manga longa. Elegante para o trabalho.",
    preco: 5990,
    categoria: "Blusas",
    tamanhos: ["P", "M"],
    fotos: ["https://placehold.co/400x600?text=Blusa+Transpassada"],
    disponivel: true,
    createdAt: "2026-07-27T14:30:00Z",
  },
  {
    id: "3",
    nome: "Saia Midi Plissada",
    descricao: "Saia plissada em poliéster. Cintura alta, comprimento midi. Preto clássico.",
    preco: 7490,
    categoria: "Saias",
    tamanhos: ["P", "M", "G", "GG"],
    fotos: ["https://placehold.co/400x600?text=Saia+Midi"],
    disponivel: true,
    createdAt: "2026-07-26T09:15:00Z",
  },
  {
    id: "4",
    nome: "Calça Pantalona",
    descricao: "Calça pantalona em linho. Cintura elástica, tecido leve. Conforto e estilo.",
    preco: 9990,
    categoria: "Calças",
    tamanhos: ["M", "G", "GG"],
    fotos: ["https://placehold.co/400x600?text=Calca+Pantalona"],
    disponivel: true,
    createdAt: "2026-07-25T16:45:00Z",
  },
  {
    id: "5",
    nome: "Jaqueta Jeans",
    descricao: "Jaqueta jeans clássica. Lavagem clara, desbotada. Botões de metal.",
    preco: 12990,
    categoria: "Jaquetas",
    tamanhos: ["P", "M", "G"],
    fotos: ["https://placehold.co/400x600?text=Jaqueta+Jeans"],
    disponivel: true,
    createdAt: "2026-07-24T11:20:00Z",
  },
  {
    id: "6",
    nome: "Colar Argentium",
    descricao: "Colar prata 950 com pedra ônix. Corrente 45cm. Acompanha estojo.",
    preco: 4990,
    categoria: "Acessórios",
    tamanhos: ["Único"],
    fotos: ["https://placehold.co/400x600?text=Colar+Argentium"],
    disponivel: true,
    createdAt: "2026-07-23T08:00:00Z",
  },
  {
    id: "7",
    nome: "Vestido Tubinho",
    descricao: "Vestido tubinho preto básico. Decote reto, mangas curtas. Tactel confortável.",
    preco: 6990,
    categoria: "Vestidos",
    tamanhos: ["P", "M", "G", "GG"],
    fotos: ["https://placehold.co/400x600?text=Vestido+Tubinho"],
    disponivel: true,
    createdAt: "2026-07-22T13:10:00Z",
  },
  {
    id: "8",
    nome: "Blusa Cropped",
    descricao: "Blusa cropped em malha gelada. Cor mostarda, decote redondo. Despojada.",
    preco: 3990,
    categoria: "Blusas",
    tamanhos: ["P", "M"],
    fotos: ["https://placehold.co/400x600?text=Blusa+Cropped"],
    disponivel: true,
    createdAt: "2026-07-21T10:30:00Z",
  },
  {
    id: "9",
    nome: "Saia Jeans",
    descricao: "Saia jeans reta. Azul médio, cintura média, fenda lateral. Use com botas.",
    preco: 5990,
    categoria: "Saias",
    tamanhos: ["M", "G"],
    fotos: ["https://placehold.co/400x600?text=Saia+Jeans"],
    disponivel: true,
    createdAt: "2026-07-20T15:00:00Z",
  },
  {
    id: "10",
    nome: "Calça Cargo",
    descricao: "Calça cargo bege. Bolsos laterais, tornozelo ajustado. Tecido sarja.",
    preco: 8490,
    categoria: "Calças",
    tamanhos: ["P", "M", "G"],
    fotos: ["https://placehold.co/400x600?text=Calca+Cargo"],
    disponivel: true,
    createdAt: "2026-07-19T09:45:00Z",
  },
  {
    id: "11",
    nome: "Jaqueta Couro",
    descricao: "Jaqueta couro legítimo. Preta, zíper diagonal, gola careca. Ícone atemporal.",
    preco: 19990,
    categoria: "Jaquetas",
    tamanhos: ["M", "G"],
    fotos: ["https://placehold.co/400x600?text=Jaqueta+Couro"],
    disponivel: true,
    createdAt: "2026-07-18T14:20:00Z",
  },
  {
    id: "12",
    nome: "Brinco Argola",
    descricao: "Par de argolas douradas. Aço banhado a ouro 18k. 5cm diâmetro.",
    preco: 2990,
    categoria: "Acessórios",
    tamanhos: ["Único"],
    fotos: ["https://placehold.co/400x600?text=Brinco+Argola"],
    disponivel: true,
    createdAt: "2026-07-17T11:00:00Z",
  },
];

export const categorias: Categoria[] = [
  { slug: "vestidos", nome: "Vestidos" },
  { slug: "blusas", nome: "Blusas" },
  { slug: "saias", nome: "Saias" },
  { slug: "calcas", nome: "Calças" },
  { slug: "jaquetas", nome: "Jaquetas" },
  { slug: "acessorios", nome: "Acessórios" },
];
